server:
  port: 8098

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sys.datasource.driver-class-name}
      url: jdbc:mysql://${sys.datasource.host}:${sys.datasource.port}/${sys.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sys.datasource.username}
      password: ${sys.datasource.password}

mybatis-plus:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sys.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  logging:
    pattern:
      console: '%d{HH:mm:ss.SSS}%clr(%-5level) --- [%-15thread]%cyan(%-50logger{50}):%msg%n'
  level:
    com:
      example:
        demo:
          mapper: debug
          service: info
          controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
